// AUTO-GENERATED by scripts/sync-codes.mjs — do not edit manually.
// Run "pnpm sync:codes" or wait for the weekly GitHub Action.
// Reward overrides: scripts/codes-sync-overrides.json

import syncState from "./codes-sync-state.json"

export type CodeStatus = "verified" | "community" | "needs-testing"

/** Mirrors lib/codes-sync-state.json for use in React server/client components. */
export const codesSyncMeta = {
  lastSyncedAt: syncState.lastSyncedAt,
  sources: syncState.sources,
  sourceResults: syncState.sourceResults,
  changelog: syncState.changelog,
} as const

export type WikiCode = {
  code: string
  reward: string
  status: CodeStatus
  /** Number of public lists that included this code on last sync. */
  sourceCount: number
  /** Human-readable source names from last sync. */
  sources: string[]
  /** ISO date when this code first appeared in our sync. */
  firstSeen: string
  isNew?: boolean
}

export type ArchivedCode = {
  code: string
  reward: string
  removedAt: string
}

export const wikiCodes: WikiCode[] = [
  {
    code: "100KVISITS",
    reward: "5-minute Time Skip (some sources report cash instead — check in-game)",
    status: "community",
    sourceCount: 10,
    sources: ["Pro Game Guides","Pocket Tactics","Radio Times","GamesRadar+","Destructoid","Beebom","buildaringfarm.net","buildaringfarm.co","buildaringfarmgame.wiki","AllThings.how"],
    firstSeen: "2026-05-31",
    isNew: true,
  },
  {
    code: "2KLIKES",
    reward: "1x Tropical Seed Pack",
    status: "community",
    sourceCount: 10,
    sources: ["Pro Game Guides","Pocket Tactics","Radio Times","GamesRadar+","Destructoid","Beebom","buildaringfarm.net","buildaringfarm.co","buildaringfarmgame.wiki","AllThings.how"],
    firstSeen: "2026-05-31",
    isNew: true,
  },
  {
    code: "BARF:3",
    reward: "1x Acid Spray",
    status: "community",
    sourceCount: 10,
    sources: ["Pro Game Guides","Pocket Tactics","Radio Times","GamesRadar+","Destructoid","Beebom","buildaringfarm.net","buildaringfarm.co","buildaringfarmgame.wiki","AllThings.how"],
    firstSeen: "2026-05-31",
    isNew: true,
  },
  {
    code: "THANKYOU",
    reward: "1x Autumn Spray",
    status: "community",
    sourceCount: 10,
    sources: ["Pro Game Guides","Pocket Tactics","Radio Times","GamesRadar+","Destructoid","Beebom","buildaringfarm.net","buildaringfarm.co","buildaringfarmgame.wiki","AllThings.how"],
    firstSeen: "2026-05-31",
    isNew: true,
  },
  {
    code: "UPDATE2",
    reward: "1x Tropical Seed Pack",
    status: "community",
    sourceCount: 10,
    sources: ["Pro Game Guides","Pocket Tactics","Radio Times","GamesRadar+","Destructoid","Beebom","buildaringfarm.net","buildaringfarm.co","buildaringfarmgame.wiki","AllThings.how"],
    firstSeen: "2026-05-31",
    isNew: true,
  },
  {
    code: "UPDATE1",
    reward: "3 Strong Fertilizers",
    status: "community",
    sourceCount: 9,
    sources: ["Pro Game Guides","Pocket Tactics","Radio Times","GamesRadar+","Destructoid","Beebom","buildaringfarm.co","buildaringfarmgame.wiki","AllThings.how"],
    firstSeen: "2026-05-31",
    isNew: true,
  },
  {
    code: "PLANTRUSH",
    reward: "1x Plant Rush Boss Box",
    status: "community",
    sourceCount: 8,
    sources: ["Pro Game Guides","Pocket Tactics","Radio Times","GamesRadar+","Destructoid","Beebom","buildaringfarm.net","buildaringfarm.co"],
    firstSeen: "2026-05-31",
    isNew: true,
  }
]

export const wikiCodesArchived: ArchivedCode[] = [
  {
    code: "RELATED",
    reward: "left corner.",
    removedAt: "2026-05-31",
  }
]

/** Display ordering: new codes first, then higher source consensus, then alphabetical. */
export const wikiCodesSorted = [...wikiCodes].sort((a, b) => {
  const aNew = a.isNew ? 1 : 0
  const bNew = b.isNew ? 1 : 0
  if (bNew !== aNew) return bNew - aNew
  if (b.sourceCount !== a.sourceCount) return b.sourceCount - a.sourceCount
  return a.code.localeCompare(b.code)
})

export function formatSyncDate(iso: string): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(iso))
}
