// AUTO-GENERATED by scripts/sync-codes.mjs — do not edit manually.
// Run "pnpm sync:codes" or wait for the weekly GitHub Action.
// Reward overrides: scripts/codes-sync-overrides.json

import syncState from "./codes-sync-state.json"

export type CodeStatus = "verified" | "community" | "needs-testing"

/** Public sync metadata — no third-party URLs exposed on the codes page. */
export const codesSyncMeta = {
  lastSyncedAt: syncState.lastSyncedAt,
  sourceCount: syncState.sources.length,
} as const

export type WikiCode = {
  code: string
  reward: string
  status: CodeStatus
  /** Number of gaming-media lists that included this code on last sync. */
  sourceCount: number
  isNew?: boolean
}

export type ArchivedCode = {
  code: string
  reward: string
  removedAt: string
}

export const wikiCodes: WikiCode[] = [
  {
    code: "100KVISITS",
    reward: "5 Minute Time Skip",
    status: "community",
    sourceCount: 7,
  },
  {
    code: "2KLIKES",
    reward: "1x Tropical Seed Pack",
    status: "community",
    sourceCount: 7,
  },
  {
    code: "BARF3",
    reward: "1x Acid Spray",
    status: "community",
    sourceCount: 7,
  },
  {
    code: "THANKYOU",
    reward: "1x Autumn Spray",
    status: "community",
    sourceCount: 7,
  },
  {
    code: "UPDATE1",
    reward: "3x Strong Fertilizer",
    status: "community",
    sourceCount: 7,
  },
  {
    code: "UPDATE2",
    reward: "1x Tropical Seed Pack",
    status: "community",
    sourceCount: 7,
  },
  {
    code: "250KUSERS",
    reward: "Time Skip (3 minutes)",
    status: "community",
    sourceCount: 6,
  },
  {
    code: "PLANTRUSH",
    reward: "1x Plant Rush Boss Box",
    status: "community",
    sourceCount: 6,
  },
  {
    code: "CARNIVAL",
    reward: "100 Carnival Pass Tickets",
    status: "community",
    sourceCount: 4,
    isNew: true,
  },
  {
    code: "UPDATE5",
    reward: "Super Pet Treat",
    status: "community",
    sourceCount: 4,
    isNew: true,
  }
]

export const wikiCodesArchived: ArchivedCode[] = [

]

/** Display ordering: new codes first, then higher source consensus, then alphabetical. */
export const wikiCodesSorted = [...wikiCodes].sort((a, b) => {
  const aNew = a.isNew ? 1 : 0
  const bNew = b.isNew ? 1 : 0
  if (bNew !== aNew) return bNew - aNew
  if (b.sourceCount !== a.sourceCount) return b.sourceCount - a.sourceCount
  return a.code.localeCompare(b.code)
})

export function formatSyncDate(iso: string): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(iso))
}
